#!/usr/bin/perl -w

use strict;
use warnings;
use Test::More tests => 38;
use File::Temp qw(tempdir);
use Cwd;

use lib 'lib';

use_ok('Alien::Package::Pacman');
isa_ok(Alien::Package::Pacman->new(), 'Alien::Package');

# Create a synthetic .pkg.tar.zst fixture.
my $tmpdir = tempdir("alien-test-XXXX", CLEANUP => 1, TMPDIR => 1);
my $pkgroot = "$tmpdir/pkg";
mkdir($pkgroot) or die "mkdir $pkgroot: $!";

# Write .PKGINFO.
open my $fh, '>', "$pkgroot/.PKGINFO" or die "$pkgroot/.PKGINFO: $!";
print $fh "# generated by test\n";
print $fh "pkgname = testpkg\n";
print $fh "pkgver = 1.2.3-2\n";
print $fh "pkgdesc = A test package\n";
print $fh "url = http://example.com\n";
print $fh "builddate = 1716769543\n";
print $fh "packager = Test User <test\@example.com>\n";
print $fh "size = 12345\n";
print $fh "arch = x86_64\n";
print $fh "license = GPL-3.0-or-later\n";
print $fh "group = default\n";
print $fh "depend = glibc>=2.38\n";
print $fh "depend = perl>=5.0\n";
print $fh "provides = testpkg\n";
close $fh;

# Write .INSTALL.
open $fh, '>', "$pkgroot/.INSTALL" or die "$pkgroot/.INSTALL: $!";
print $fh qq{post_install() {\n\techo "installed"\n}\n};
print $fh qq{pre_remove() {\n\techo "removing"\n}\n};
close $fh;

# Write package files.
mkdir("$pkgroot/etc") or die;
open $fh, '>', "$pkgroot/etc/foo.conf" or die;
print $fh "config = true\n";
close $fh;

mkdir("$pkgroot/usr")       or die;
mkdir("$pkgroot/usr/bin")   or die;
open $fh, '>', "$pkgroot/usr/bin/testpkg" or die;
print $fh "#!/bin/sh\necho hello\n";
close $fh;

# Build the .pkg.tar.zst.
my $test_file = "$tmpdir/testpkg-1.2.3-2-x86_64.pkg.tar.zst";
my $save_cwd = Cwd::cwd();
chdir $tmpdir;
my $ret = system("tar --zstd -cf '$test_file' -C '$pkgroot' "
    . ".PKGINFO .INSTALL etc/foo.conf usr/bin/testpkg 2>/dev/null");
chdir $save_cwd;
ok($ret == 0 && -f $test_file, "Test fixture created");

# Instantiate and read.
my $pkg = Alien::Package::Pacman->new(filename => $test_file);
isa_ok($pkg, 'Alien::Package::Pacman');

is($pkg->name,              'testpkg',                       'name');
is($pkg->version,           '1.2.3',                         'version');
is($pkg->release,           '2',                             'release');
is($pkg->arch,              'amd64',                         'arch (x86_64 -> amd64)');
is($pkg->summary,           'A test package',                'summary');
is($pkg->description,       'A test package',                'description');
is($pkg->depends,           'glibc>=2.38, perl>=5.0',        'depends (multi-line concat)');
is($pkg->provides,          'testpkg',                       'provides');
is($pkg->copyright,         'GPL-3.0-or-later',              'copyright');
is($pkg->group,             'default',                       'group');
is($pkg->maintainer,        'Test User <test@example.com>',  'maintainer');
is($pkg->origformat,        'pacman',                        'origformat');
is($pkg->distribution,      'Arch Linux',                    'distribution');

my $files = $pkg->filelist;
is(scalar @{$files}, 2, 'file count (2 regular files)');
ok((grep { m|/etc/foo\.conf$| } @{$files}),  'filelist includes /etc/foo.conf');
ok((grep { m|/usr/bin/testpkg$| } @{$files}), 'filelist includes /usr/bin/testpkg');

ok(defined $pkg->postinst && $pkg->postinst =~ /installed/,
   '.INSTALL post_install body transcribed');
ok(defined $pkg->prerm && $pkg->prerm =~ /removing/,
   '.INSTALL pre_remove body transcribed');

# =========================================================================
# build() round-trip tests
# =========================================================================

{
# Build a package from synthetic object state.
my $builddir = tempdir("alien-build-XXXX", CLEANUP => 1, TMPDIR => 1);
system("mkdir -p '$builddir/usr/bin'") == 0 or die "mkdir usr/bin failed";
system("mkdir -p '$builddir/etc'") == 0 or die "mkdir etc failed";
open my $fh2, '>', "$builddir/usr/bin/testpkg" or die;
print $fh2 "#!/bin/sh\necho hello\n";
close $fh2;
open $fh2, '>', "$builddir/etc/foo.conf" or die;
print $fh2 "config=true\n";
close $fh2;

my $builder = Alien::Package::Pacman->new();
$builder->name('testpkg');
$builder->version('1.2.3');
$builder->release('2');
$builder->arch('amd64');
$builder->summary('A test package');
$builder->copyright('GPL-3.0-or-later');
$builder->maintainer('Test User <test@example.com>');
$builder->depends('glibc>=2.38, perl>=5.0');
$builder->provides('testpkg');
$builder->buildtree($builddir);

my $save_cwd2 = Cwd::cwd();
chdir $tmpdir;
my $built_file = $builder->build();
chdir $save_cwd2;

ok(defined $built_file, 'build() returned a filename');
ok(-f "$tmpdir/$built_file", 'built package file exists');
ok(-s "$tmpdir/$built_file" > 0, 'built package has nonzero size');

# Re-read the built file through a fresh scan.
my $re_read = Alien::Package::Pacman->new(filename => "$tmpdir/$built_file");
is($re_read->name,       'testpkg',           'round-trip name');
is($re_read->version,    '1.2.3',             'round-trip version');
is($re_read->arch,       'amd64',             'round-trip arch');
is($re_read->summary,    'A test package',    'round-trip summary');

my $re_files = $re_read->filelist;
is(scalar @{$re_files}, 2, 'round-trip file count');
}

# =========================================================================
# Phase 4: test(), unpack(), install() smoke tests
# =========================================================================

{
# test() — container integrity + metadata sanity.
my $result = $pkg->test;
ok(defined $result, 'test() returns success');
}

{
# unpack() — extract files into buildtree, skip metadata.
my $unpackdir = $pkg->unpack;
ok(defined $unpackdir,  'unpack() returns a directory');
ok(-d $unpackdir,       'unpack directory exists');
ok(-f "$unpackdir/etc/foo.conf",     'unpacked /etc/foo.conf');
ok(-f "$unpackdir/usr/bin/testpkg",  'unpacked /usr/bin/testpkg');
ok(!-f "$unpackdir/.PKGINFO",        'unpacked excludes .PKGINFO (metadata)');
}

{
# install() — mock do() to capture the command.
my $captured;
local *Alien::Package::do = sub {
	my $self = shift;
	$captured = join(' ', @_);
	return 1;
};
local *Alien::Package::Pacman::_inpath = sub { return 1 };
my $install_pkg = Alien::Package::Pacman->new();
$install_pkg->install($test_file);
like($captured, qr/pacman -U/,           'install() calls pacman -U');
like($captured, qr/\Q$test_file\E/,      'install() includes filename');
}
